### ISSUE TITLE
Investigate posting images with social media share

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#1021]
Share relevant static image (destination image or blog post image) when sharing to social media.

**Comment by flibbertigibbet** [comment]
Blocked by #1023

**Comment by lederer** [comment]
I interpreted the issue here as unrelated to sharing buttons per se, in which case #1023 need not be a blocker. As long as the page has a legit `<meta property="og:image" … >` tag, the preview image should show up in FB regardless of the sharing mechanism (eg, share button vs. manually pasting the link into FB). I think that was the only real concern.

@flibbertigibbet @jcahail Were your takeaways different?

**Comment by flibbertigibbet** [comment]
We have `og:image` tags set already for the relevant pages, so not sure what else we should be doing.

Was thinking of explicitly setting the image via a share dialog, to hopefully have more control over what the resulting post looks like.

**Comment by lederer** [comment]
Interesting.  [Facebook's Sharing Debugger](https://developers.facebook.com/tools/debug/sharing/) doesn't seem to be finding the `og:image`. Seems to often think it's the logo, even when it's set in the html to something else.

Seems to be using the homepage as the scraped page, instead of the actual detail page itself. I think it may be due to `og:url` being set to the homepage, even for detail pages.

![image](https://user-images.githubusercontent.com/128699/38505908-5a5ace02-3be6-11e8-9000-e50ca67c7572.png)

**Comment by flibbertigibbet** [comment]
I wonder if the incorrect image reference found by the Facebook sharing debugger is possibly is related to the redirects on the canonical URL:

![image](https://user-images.githubusercontent.com/960264/38583005-9d69f098-3cdf-11e8-985a-9acf3ead781c.png)

**Comment by flibbertigibbet** [comment]
Looks like the image tags have a relative path. They should be absolute to resolve.

On current production, they look like:
`<meta property="og:image" content="/media/destinations/57a2720ffafd41649676b1646ed5e90c.jpg.680x400_q85_box-destinations/57a2720ffafd41649676b1646ed5e90c.jpg_crop_detail.jpg">`

**Comment by flibbertigibbet** [comment]
Images seem to be getting parsed correctly now, according to the Facebook graph debugger:

### A place
![facebook_graph_debugger_place_detail](https://user-images.githubusercontent.com/960264/43741387-29b85e04-999c-11e8-94de-0468d5d7c722.png)

### The home page (now using the new image)

![facebook_debug_gophillygo](https://user-images.githubusercontent.com/960264/43741401-3b45777e-999c-11e8-9968-4b7b03ef12f5.png)

**Comment by flibbertigibbet** [comment]
An article:

![image](https://user-images.githubusercontent.com/960264/43741457-6132aac4-999c-11e8-9291-2d5339777d43.png)
