### ISSUE TITLE
Compile list of changes made in this phase

### ISSUE THREAD

**Issue by jcahail** [azavea/cac-tripplanner#1031]
For CAC's interim report to the grantmaker (due 4/25). Our deadline to get the info to Nick is no later than 4/24.

**Comment by flibbertigibbet** [comment]
## Changes in the past year, based on release notes, oldest first:
 
- Expanded address completion search area to cover southern Delaware.
 - Updates OpenTripPlanner version to 1.2.0.
 - Includes new feature for summary of travel times and distances per mode.
 - Make web app a progressive web app (can "install to home screen")
 - Show user location on mobile devices
 - Style updates
 - Dependency updates
 - Switches data source for Indigo bike share feeds
 - List places in directions sidebar when destination not populated
 - Adds new Event type and adds fields to Destination objects for accessibility, watershed alliance centers, and available activities, which may now be set in the administrative interface.
 - Filter destinations and events by category
 - Display new destination attributes (Watershed Alliance badge, accessibility, available activities)
 - Modify bicycle routing behavior to use OTP optimize flag GREENWAYS for "safe" mode, and make "safe" mode the default
 - Use exact marker location on marker drag when getting directions (not reverse-geocoded address displayed)
 - Improves handling of multiple sequential trip requests.
 - Disable travelshed slider when origin not set
 - Display travel distance instead of time on place cards when origin set
 - Fix timeouts on querying for large travelsheds with bike and transit
