### ISSUE TITLE
Errant back button when getting directions to event location

### ISSUE THREAD

**Issue by lederer** [azavea/cac-tripplanner#1195]
- Open a multi-location event map.
- Ensure no origin is set.
- Click Directions on any location.
- Sidebar appears empty except for recently introduced back button. (screenshot below)
- Enter an origin.
- When itineraries appear, back button is no longer visible.

Preferred solution:
- After clicking Directions, the back button is hidden, and a "Choose an origin" message is shown.
- After entering an origin, the back button is visible (assuming implementation isn't too complex).

![image](https://user-images.githubusercontent.com/128699/67865547-cfb61f80-fafd-11e9-9e3e-1f4d995afc95.png)

**Comment by flibbertigibbet** [comment]
The sidebar is only empty on clicking the first destination on the list without an origin set, as there is no previous location to route from.

Setting the origin or otherwise changing the routing settings will hide the back button, because it updates the URL and so changes the browser back history. Controlling state to track whether the user logically came from a tour beyond the last URL is outside the scope as we discussed it for adding this button, which is for it to match the back button behavior.

**Comment by lederer** [comment]
> The sidebar is only empty on clicking the first destination on the list without an origin set, as there is no previous location to route from.

True when it's a tour. When it's a multi-location event, getting Directions to a location always has an empty origin.

> Controlling state to track whether the user logically came from a tour beyond the last URL is outside the scope as we discussed it for adding this button, which is for it to match the back button behavior.

That's fine. Please just hide the back button so it doesn't appear while the sidebar is empty.

**Comment by flibbertigibbet** [comment]
Oh, I see, it's also showing on events. That is unrelated to the sidebar being empty (I understand you want it hidden in that case as well).

**Comment by flibbertigibbet** [comment]
Closed in #1198
