### ISSUE TITLE
Upgrade Postgresql

### ISSUE THREAD

**Issue by stephwall** [azavea/cac-tripplanner#1298]

**Comment by ddohler** [comment]
@stephwall This needs to happen by January 18th, or we'll be forcibly upgraded by AWS. I don't expect major issues with this app because we're not using any special features that I know of.

**Comment by ddohler** [comment]
Since we don't have a staging environment, we are going to apply this directly to production. I've tested in development and confirmed that the application is functional after upgrading the database to Postgresql 12, which aligns with our general expectation that database usage for this application generally sticks to well-trod paths and that we shouldn't expect difficulties with this upgrade. I'm creating the following production upgrade checklist based on the steps followed for other applications that have already been upgraded and my own research into the application's infrastructure.

## Upgrade Bastion
- [x] Build new Bastion AMI (the bastion is running Ubuntu 14.04, which is unsupported both by Canonical and by the Postgresql maintainers, so we need to upgrade in order to install a compatible `psql` version https://www.postgresql.org/download/linux/ubuntu/ . All other infrastructure is running 18.04 already): `AWS_PROFILE=gophillygo deployment/cac-stack.py create-ami --machine-type bastion` . When the AMI build finishes, note down the generated AMI ID.
- [x] Log in to the AWS console using the GoPhillyGo credentials in LastPass
- [x] Initiate drift detection for the VPC stack (which includes the Bastion) in the AWS Cloudformation console. Then view the drift detection results and resolve any discrepancies that you can manually. https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/drifts?stackId=arn%3Aaws%3Acloudformation%3Aus-east-1%3A204768116391%3Astack%2FVPC-24f053d8a472e0d1fa9a945797ce%2F184b5e90-ed1b-11e4-a669-50e2416294a8 (I encountered duplicate tag keys, which I was unable to resolve manually, but they seem unlikely to be harmful, so I decided to leave them alone).
- [x] Go to CloudFormation, select `VPC-24f053d8a472e0d1fa9a945797ce` → Change sets → Create change set
- [x] Select "Use current template" and update the BastionHostAMI with the value from the AMI build
- [x] Click Next. I changed the `StackType` tag to have the value `VPC` instead of `Production` because this seemed to be the cause of some of the drift detected earlier; my hope is that resetting the value of one of the duplicated tags will clear out the duplicates.
- [x] In the description box, write "Upgrading Bastion to Ubuntu Bionic", and create it
- [x] Once the change set finishes being created, review the list of changes to be sure that nothing looks unexpected
- [x] Assuming all looks well, "Execute" the change set. Choose to execute it immediately, rather than in a scheduled window
- [x] Observe the change set being executed. In case of failures, you'll see reasons for them in CloudFormation's DataPlan → Events. Fix them and try again.
- [x] Once the new Bastion is up, ensure you can SSH into it using the `cac.pem` file
- [x] From within the Bastion, try SSHing in to the App or OTP VM to ensure that still works
- [x] Follow [the official instructions to add the Postgresql Ubuntu repository](https://www.postgresql.org/download/linux/ubuntu/) (but don't follow the instructions for installing because we want a specific version, not just whatever's latest).
- [x] Install postgres-client-12: `sudo apt install postgres-client-12`

## Upgrade PostGIS
Postgresql 12, which we're targeting, doesn't support the current version of PostGIS (2.3): https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS . Our development environments have gotten out of sync with our RDS environment and are running PostGIS 3.0 already, so it is expected to be compatible with the app.

- [ ] Take a Database Snapshot (in theory this should happen automatically prior to Postgresql version upgrade because we have database backups enabled but it doesn't hurt to take one manually ahead of the PostGIS upgrade to be extra safe).
- [ ] Log in to AWS using the GoPhillyGo credentials in LastPass
- [ ] Go to RDS, select Snapshots → Take snapshot, and name it "pre-postgres-upgrade"
- [ ] Create a named tmux session `tmux new -s psql`
- [ ] Connect to the database: `psql -U cac_tripplanner -d cac_tripplanner -h database.service.cac.internal`
- [ ] Upgrade PostGIS:

```sql
SELECT * FROM pg_available_extensions WHERE installed_version IS NOT NULL;
SELECT * FROM pg_available_extension_versions WHERE name in ('postgis', 'plpgsql');

ALTER EXTENSION postgis UPDATE TO 2.5; --There have been reported issues upgrading from 2.3 directly to 3.0

SELECT PostGIS_Extensions_Upgrade(); --Upgrade the rest of the way to 3.0

DROP EXTENSION postgis_raster; --This may not be necessary when upgrading to 2.5 first
```

## Upgrade to Postgresql 12
This is the highest version we can go with the current version of `psycopg2` (2.8.6), so it's the highest version we can get to without rebuilding the `app` AMI and redeploying.
- [ ] Go to RDS → Parameter Groups → Create parameter group, and make one based off the default Postgres 12 group and call it `gophillygo-postgres12`
- [ ] Go to RDS → Databases → <database ID> → Modify
- [ ] Set DB engine version to 12.8, DB parameter group to `gophillygo-postgres12`
- [ ] Click "Continue"
- [ ] Select "Apply Immediately", and click "Modify DB Instance"
- [ ] To see the progress, go to <database ID> → Logs & Events, and sort the Logs by "Last Written" in descending order
- [ ] Open the most recent log to see the upgrade output
- [ ] In psql, check the installed version of Postgres to ensure it is 12.8: `SELECT version();`
- [ ] In psql, vacuum the database

```sql
SET maintenance_work_mem='2GB'; --We have 4GB of memory total and 3.1GB is typically free
\timing
VACUUM (FREEZE, ANALYZE, VERBOSE);
```

- Verify application functionality as you would during a deploy.

**Comment by ddohler** [comment]
@BryanQuigley Can you take a look at the revised checklist and make sure this matches your memory of what we did? I'm realizing that we forgot to vacuum afterward, so I'm making a note for myself to do that.

**Comment by BryanQuigley** [comment]
LGTM
