### ISSUE TITLE
Investigate Taking Down Android App

### ISSUE THREAD

**Issue by rajadain** [azavea/cac-tripplanner#1366]
The Android App is expired and should be taken down.

Investigate and document the process of taking the app down. Once the process is established, wait for client's green light.

Make a follow up card to actually do the take down.

**Comment by JN-Hernandez** [comment]
# High Level Investigation

The following items should be explored in order to determine scope of the tear-down.

- [ ] Notifications and communication
	- [ ] Marketing updates
	- [ ] Customer base (any alternatives?)
	- [ ] `README` verbiage update
- [ ] Determine what backups will need to be made, if any
	- [ ] Any user data being stored
	- [ ] Any application data being stored
- [ ] Archiving the GitHub Repo
- [ ] Remove from Google Play 
- [ ] Removing notifications
	- [ ] Slack notifications
	- [ ] Firebase crash reporting
	- [ ] Rollbar notifications
- [ ] Rollback Plan
	- [ ] Determine if there is a need for rollback/publishing the app again

# Additional Information

**12/12/23, 16:39 Eastern**: This comment will be updated with findings as the investigation continues.
