### ISSUE TITLE
Autocomplete results enhancements

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#154]
*   Some destinations don't autocomplete (King of Prussia Mall, Longwood Gardens) - this may be related to the extent of the suggest/search radius
*   City/area names don't geocode (i.e. East Falls)
*   Should discuss options when a user's search can't be resolved
*   This kind of needs to work as well as Google Maps (I know) - we may want to consider switching libraries
*   This was the primary hindrance to usability
*   Requires discussion

**Comment by flibbertigibbet** [comment]
Partially addressed by #191, although now the bounding box has been extended, some unlikely/distant suggestions sometimes pop up first.

**Comment by CloudNiner** [comment]
You could try a center and radius instead, so that it prefers closer destinations? But, that has other potential issues.

**Comment by flibbertigibbet** [comment]
Yeah, been playing with that, and found that it only works without the search extent parameter, although the documentation seems to imply they can be used together.

**Comment by jbranigan** [comment]
This is working better than before. We used to be able to search by business names, too, but that seems to have gone away. Also, getting Texas addresses... let's tune this a bit.

**Comment by flibbertigibbet** [comment]
Due to an open issue with ESRI's suggestion service, it is not possible to specify both a bounding box and a location from which to preferentially sort places by distance.  It's supposed to be fixed in a release this summer.  So, if the user's current location is found, that's used to sort by distance... you shouldn't see anything distant, unless there's nothing nearer found.

I disabled the POIs after I discovered that not only was it going to result in duplicate responses for all of our featured locations, for which we have our own autocomplete source, but many of them had totally wrong locations, despite being Philadelphia addresses (would move the map to somewhere in the ocean off Hawaii, etc.).  Maybe we can limit to sub-categories that don't overlap and have accurate results.  After adding postal addresses as a separate category, a lot of the suggested place names seemed to work pretty well.
