### ISSUE TITLE
Maximum bike distance

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#159]
Not sure if this is an option. Example = 15 miles as max en route to Conshohocken. Do we send the user up the river trail, or on the Conshy train?

**Comment by flibbertigibbet** [comment]
There is no max bike distance option, which is why I switched to max walk distance.  The reason max walk distance exists is for figuring out how far to walk to get to/from transit stops, since a longer walk can result in a shorter overall trip.  For bike+transit, the max "walk" distance seems to be getting ignored; planning a bike+transit trip to Conshohocken with a large max walk results in a single itinerary that seems to use transit as much as possible, even for downtown connections.
