### ISSUE TITLE
current location is wrong

### ISSUE THREAD

**Issue by nickrogers** [azavea/cac-tripplanner#258]
![image](https://cloud.githubusercontent.com/assets/12200440/7482132/331cdc02-f343-11e4-8b33-eeff82523515.png)
Our office is on Rittenhouse, this shows us on Arch Street.

**Comment by jbranigan** [comment]
I initially was opposed to including current location because of this. Desktop and laptop computers don't have GPS chips - the browser is guessing based on IP address / wifi network and the accuracy is dependent on some external database. Is the convenience vs. risk of inaccuracy worth keeping this feature?

**Comment by jbranigan** [comment]
Possibly - I'd like a developer to weigh in on the feasibility. Might also be able to check the accuracy property returned by the API and only use locations with accuracy beneath a particular threshold (e.g. 20 meters).

Another option would be to include a "target" icon that the user would click to turn on current location, rather than it being enabled by default. That also seems less intrusive to me, since it's an opt-in feature.

**Comment by kshepard** [comment]
Closed by #314
