### ISSUE TITLE
Home page designs

### ISSUE THREAD

**Issue by jbranigan** [azavea/cac-tripplanner#414]
@WarkulwizDesign, @nickrogers

I'm getting some pushback from the design team here about the design of the home page. A few specific items are:
-   The use of all-caps for the "GOPHILLYGO IS A NEW ONLINE MAPPING TOOL FOR THE GREATER PHILADELPHIA AREA" tag line
-   The tag line itself does not communicate what the site is about
-   The map background is too busy, and a photo of a person / people would be more appropriate and engaging than a map that doesn't look like anything else on the site
-   The size of the "2 easy ways" text is large and distracting

At this point, it's a bit late to make major changes, unfortunately. Can we get a different image for this space? If it has to be a map, can we get a version with the labels and the blue coloring turned off? The team here will provide the necessary color treatments. Also, is there a better tag line? Maybe something about sustainable transportation, bicycling, new destinations, etc.

We can capital case the text, and shrink the directions a bit, if you approve.

cc: @jfrankl @ctaylo37

**Comment by jfrankl** [comment]
From our experience, it is helpful for the tagline to tell the user what they can expect to get out of the application and how it will help solve their problems. Here are a few ideas for the tagline that I believe will communicate to users what the application is about and why they would want to use it:

- Plan your next adventure. Explore Philadelphia on foot, bike, and transit. **(Preferred)**
- Explore Philadelphia on foot, bike, and public transit.

**Comment by WarkulwizDesign** [comment]
We appreciate your suggestions on this, however the GPG team has worked with CAC to achieve an aesthetic that works across multiple medias, including the live site, so it is important that we stick to what we have provided. 
- For the tagline, if caps is what is throwing this off, then let's do sentence case. Please treat GoPhillyGo (capital G, P, and G) because that is how it is treated on advertising and social media. 

- As for what the tagline (headline) reads as, lets change it to:
GoPhillyGo is a new online mapping tool for the Greater Philadelphia area that helps you combine multiple modes into one trip.

The current tagline that is used on all current advertising for transit ads, online ads, and the print piece that will be distributed to the press and concierges in the future. This is the tagline for Phase I. advertising. This tagline can be updated as the site adapts and progresses through the year. This is the first thing a user sees when they log onto the computer and it explains what the site is about.

- We've worked with CAC to create art that represents the introduction of the website that is also used on any of our advertising. Since it is a mapping website, we are proceeding with the map art since we feel it best represents what the site is about in the introduction phase. Moving forward, we can change the art as the site and advertising evolves. 

For the image used, the map used on the staging site is not the correct map. See this dropbox link:
flat png file with color overlay: 
https://www.dropbox.com/s/ydh0p66ij71oa2j/150624-GPG-Map-Cover.png?dl=0

flat png file without color overlay: 
https://www.dropbox.com/s/c3zoxhadpl6ti4p/150629-GPG-Map-Only-Cover.png?dl=0

layered ai file in the case you need more image. The map file is currently masked to fit the 2800x800 px ratio but the art is very large and can be extended if needed.: https://www.dropbox.com/s/vk7k6492n787lee/150624-GPG-Map-Cover.ai?dl=0

It is up to you how you want to use the color overlay - which is hex 66b5eb at 60% opacity. The color overlay is meant here to allow the type to read effectively, but in the future we may not want to use it on other photography or illustration. 

- Leave ' 2 easy ways' text as is. From watching the user testing, CAC and the GPG team noticed it was hard to tell that 'explore' and 'help me..' are even buttons. Letting the user know what to do here is key.

**Comment by jbranigan** [comment]
Update tagline to describe what the site does / replace map image with something more engaging, as the site advertising evolves.

**Comment by flibbertigibbet** [comment]
Old issue, closing.
