### ISSUE TITLE
Vagaries of out-of-bound destination routes and data

### ISSUE THREAD

**Issue by CorynWolk** [azavea/cac-tripplanner#438]
The user tried to plan multimodal trips to a few points in Ocean County and Cape May County, and along the Atlantic City Line. Sometimes GoPhillyGo allowed him to plan trips outside its typical scope, sometimes not. For example, it allowed him to plan a trip to roughly 23 Nautilus Blvd, Lacey Twp, NJ, including bus lines out there. (It looks like he was actually able to plan the trip with just a nearby intersection, but I couldn’t consistently replicate that.) But some Atlantic City Line stops (such as the Absecon Transfer Point) are not in the database, while others, such as Egg Harbor, appear as an option but the site doesn’t actually let you plan a trip to them. I told him that GoPhillyGo seems to allow some fluke trips to be planned outside its scope depending on what data it has on transit in those areas, but are there any consistent rules to what will work or not? If the site doesn’t always reject queries to areas outside of the DVRPC region, we might want to make sure people know that getting results for those queries is an exception to the rule and that the resulting routes may not be based on complete information.

**Comment by jbranigan** [comment]
I thought we were displaying a message that a certain trip was outside of the project area? If not, we can add that. @flibbertigibbet?

**Comment by flibbertigibbet** [comment]
It does display a message for trips with starting or ending points outside the map bounds. The transit network extends beyond the map bounds, but the only way to get a trip back outside the bounds would be to set a start/end point that exactly coincides with a transit stop when using transit as a mode.

If you're referring to results in the geocoder that aren't in the DVRPC region, that's because the limiting region to the geocoder is a bounding box and not a more complex polygon. The bounding box is set to include the full DVRPC region, and so also includes some areas beyond the DVRPC counties. On attempting to route a trip to a place allowed by the geocoder but beyond the map bounds, the trip planner will return the message that it is outside the bounds.
