### ISSUE TITLE
Get Directions button on the place detail page not implemented

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#768]
Added in #760

**Comment by flibbertigibbet** [comment]
Problematic as the place detail page is currently static.

**Comment by flibbertigibbet** [comment]
As there is no JS loaded on the places detail page, there is neither an origin to reference nor a reference to the JS directions controller we use on the home page to load directions, so this will be non-trivial to implement.

**Comment by KlaasH** [comment]
My comment on PR #770:
Since URL links to directions works, we could provide a link to the directions view with only the destination filled in, like we do if someone clicks a directions button under "Places we love" without having filled in an origin.  The destination is already in the template, so I think `href="/?destination={{ destination.point.y }}%2C{{ destination.point.x }}&destinationText={{ destination.name|urlencode }}"` would do it.
