### ISSUE TITLE
Display events in UI

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/cac-tripplanner#911]
Query for and present events in app alongside destinations. Show extra events fields (start and end date/times, and possibly an associated destination).

**Comment by flibbertigibbet** [comment]
Blocked by #910.

**Comment by flibbertigibbet** [comment]
See https://marvelapp.com/ae7jfde

**Comment by flibbertigibbet** [comment]
Blocked by #934

**Comment by lederer** [comment]
We need to determine the correct behavior for when there are no upcoming events to display.

Options:
1. Hide the events tab/filter completely.
1. Show a message.

I recommend showing a message, since (1) conditionally hiding the feature might confuse people who expect it, and (2) even when there's no event content, the presence of the feature naturally promotes itself to newcomers.

We'll need a better message than the current holdover from the pre-events era:

![image](https://user-images.githubusercontent.com/128699/34180080-5d1a2b4a-e4db-11e7-9d01-705cfe36ec2f.png)

**Comment by flibbertigibbet** [comment]
The existing, complicated message display rules [from here](https://github.com/azavea/cac-tripplanner/issues/873#issuecomment-320709646) will need to be updated generally for the new filtering.
